=== nasa/Mixed-Reality-Exploration-Toolkit/Schema/XSD/SchemaFiles/v0.1/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/MRET"
	elementFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:mt="http://www.example.org/MRET">

	<complexType name="ConfigurationType">
		<sequence>
			<element name="AssetsPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="EnvironmentsPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="AssetBundlesPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="FBXPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="ProjectsPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="TemplatesPath" type="string" minOccurs="1" maxOccurs="1"/>
            <element name="TypeMapPath" type="string" minOccurs="0" maxOccurs="1"/>

			<element name="HudPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="AudioRecordingPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="TextAnnotationPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="AnimationsPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="MarkersPath" type="string" minOccurs="1" maxOccurs="1" />
			<element name="PointCloudsPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="TimeSimulationPath" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="TerrainsPath" type="string" minOccurs="1" maxOccurs="1" />
			
            <element name="UserPath" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="PreferencesPath" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="RMITPath" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="SpiceKernelPath" type="string" minOccurs="0" maxOccurs="1"/>

			<element name="PlacementMode" type="boolean" minOccurs="0" maxOccurs="1" default="false"/>
			<element name="Avatars" type="boolean" minOccurs="0" maxOccurs="1" default="false"/>
			<element name="VoiceControl" type="boolean" minOccurs="0" maxOccurs="1" default="false"/>

			<element name="XmlValidation" minOccurs="0" maxOccurs="1" default="false">
    			<complexType>
					<simpleContent>
						<extension base="boolean">
							<attribute name="type" type="mt:XmlValidationType" use="optional" default="Warning"/>
						</extension>
					</simpleContent>
				</complexType>
			</element>
			
			<element name="ColliderMode">
				<simpleType>
					<restriction base="string">
						<enumeration value="None"/>
						<enumeration value="Box"/>
						<enumeration value="NonConvex"/>
					</restriction>
				</simpleType>
			</element>

		</sequence>
		<attribute name="Version" type="string"/>
	</complexType>

    <simpleType name="XmlValidationType">
        <restriction base="string">
            <enumeration value="None"/>
            <enumeration value="Warning"/>
            <enumeration value="Error"/>
        </restriction>
    </simpleType>

	<element name="Configuration" type="mt:ConfigurationType"/>
</schema>

=== nasa/Mixed-Reality-Exploration-Toolkit/Schema/XSD/SampleXMLs/v0.1/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Q1:Configuration
    xmlns:Q1="http://www.example.org/MRET"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/MRET ../../SchemaFiles/v0.1/Configuration.xsd ">

  <!-- DO NOT MODIFY BEFORE THIS LINE. -->
  <!-- Default path (relative to the application datapath) for part/asset files. -->
  <Q1:AssetsPath>Content/Standard_MRET_Content/Parts</Q1:AssetsPath>

  <!-- Default path (relative to the application datapath) for environment files. -->
  <Q1:EnvironmentsPath>Content/Standard_MRET_Content/Environments</Q1:EnvironmentsPath>

  <!-- Default path (relative to the application datapath) for asset bundle files. -->
  <Q1:AssetBundlesPath>StreamingAssets/Windows</Q1:AssetBundlesPath>

  <!-- Default path (relative to the application datapath) for asset bundle files. -->
  <Q1:FBXPath>Content/Standard_MRET_Content/FBX</Q1:FBXPath>

  <!-- Default path (relative to the application datapath) for project files. -->
  <Q1:ProjectsPath>Content/Standard_MRET_Content/Projects</Q1:ProjectsPath>
  
  <!-- Default path (relative to the application datapath) for project template files. -->
  <Q1:TemplatesPath>Content/Standard_MRET_Content/Templates</Q1:TemplatesPath>

  <!-- Default path (relative to the application datapath) for HUD files. -->
  <Q1:HudPath>Content/Standard_MRET_Content/HUDs</Q1:HudPath>
  
  <!-- Default path (relative to the application datapath) for audio recording files. -->
  <Q1:AudioRecordingPath>Content/Standard_MRET_Content/AudioRecordings</Q1:AudioRecordingPath>

  <!-- Default path (relative to the application datapath) for text annotation files. -->
  <Q1:TextAnnotationPath>Content/Standard_MRET_Content/TextAnnotations</Q1:TextAnnotationPath>

  <!-- Default path (relative to the application datapath) for animation files. -->
  <Q1:AnimationsPath>Content/Standard_MRET_Content/Animations</Q1:AnimationsPath>

  <!-- Default path (relative to the application datapath) for point cloud files. -->
  <Q1:PointCloudsPath>Content/Standard_MRET_Content/PointClouds</Q1:PointCloudsPath>

  <!-- Default path (relative to the application datapath) for time simulation files. -->
  <Q1:TimeSimulationPath>Content/Standard_MRET_Content/TimeSimulations</Q1:TimeSimulationPath>

  <!-- Default path (relative to the application datapath) for terrain files. -->
  <Q1:TerrainsPath>Content/Standard_MRET_Content/Terrains</Q1:TerrainsPath>

  <!-- Default user path. Created in the user home directory if not specified
  <Q1:UserPath>.mret</Q1:UserPath>
  -->
  
  <!-- Whether or not to enable snap placement mode. -->
  <Q1:PlacementMode>false</Q1:PlacementMode>

  <!-- Whether or not to enable avatars. -->
  <Q1:Avatars>false</Q1:Avatars>

  <!-- Whether or not to enable voice control. -->
  <Q1:VoiceControl>false</Q1:VoiceControl>

  <!-- Whether or not to validate XML and the type of response when validation is violated. -->
  <Q1:XmlValidation type="Error">true</Q1:XmlValidation>
  
  <!-- Type of collider that will be auto-applied to objects missing colliders.
       Options:
          None - no collider is applied
          Box - box collider is applied to the mesh bounds
          NonConvex - non-convex collider (voxel colliders) is applied -->
  <Q1:ColliderMode>Box</Q1:ColliderMode>
  
  <!-- DO NOT MODIFY AFTER THIS LINE. -->
</Q1:Configuration>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Q1:Configuration xmlns:Q1="http://www.example.org/MRET" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/MRET Configuration.xsd ">
  <!-- DO NOT MODIFY BEFORE THIS LINE. -->

  <!-- Default path (relative to the application datapath) for part/asset files. -->
  <Q1:AssetsPath>Content/Parts</Q1:AssetsPath>

  <!-- Default path (relative to the application datapath) for environment files. -->
  <Q1:EnvironmentsPath>Content/Environments</Q1:EnvironmentsPath>

  <!-- Default path (relative to the application datapath) for asset bundle files. -->
  <Q1:AssetBundlesPath>StreamingAssets/Windows</Q1:AssetBundlesPath>

  <!-- Default path (relative to the application datapath) for asset bundle files. -->
  <Q1:FBXPath>Content/FBX</Q1:FBXPath>

  <!-- Default path (relative to the application datapath) for project files. -->
  <Q1:ProjectsPath>Content/Projects</Q1:ProjectsPath>
  
  <!-- Default path (relative to the application datapath) for project template files. -->
  <Q1:TemplatesPath>Content/Templates</Q1:TemplatesPath>

  <!-- Default path (relative to the application datapath) for HUD files. -->
  <Q1:HudPath>Content/Huds</Q1:HudPath>
  
  <!-- Default path (relative to the application datapath) for audio recording files. -->
  <Q1:AudioRecordingPath>Content/AudioRecordings</Q1:AudioRecordingPath>

  <!-- Default path (relative to the application datapath) for text annotation files. -->
  <Q1:TextAnnotationPath>Content/TextAnnotations</Q1:TextAnnotationPath>

  <!-- Default path (relative to the application datapath) for animation files. -->
  <Q1:AnimationsPath>Content/Animations</Q1:AnimationsPath>

  <!-- Default path (relative to the application datapath) for point cloud files. -->
  <Q1:MarkersPath>Content/Markers</Q1:MarkersPath>

  <!-- Default path (relative to the application datapath) for point cloud files. -->
  <Q1:PointCloudsPath>Content/PointClouds</Q1:PointCloudsPath>

  <!-- Default path (relative to the application datapath) for time simulation files. -->
  <Q1:TimeSimulationPath>Content/TimeSimulations</Q1:TimeSimulationPath>

  <!-- Default path (relative to the application datapath) for terrain files. -->
  <Q1:TerrainsPath>Content/Terrains</Q1:TerrainsPath>

  <!-- Default user preferences path. Created in the user home directory if not specified
  <Q1:PreferencesPath>.mret</Q1:PreferencesPath>
  -->
  
  <!-- RMIT installation path. If not specified, RMIT is not available -->
  <!-- https://github.com/nasa/Rapid-Model-Import-Tool -->
  <!--
  <Q1:RMITPath>C:\Program Files\RMIT_V2.0_Release</Q1:RMITPath>
  -->
  
  <!-- Spice Kernel path (relative to the application datapath) for the SpiceToolkit meta kernel. -->
  <Q1:SpiceKernelPath>Content/SPICE</Q1:SpiceKernelPath>

  <!-- Whether or not to enable snap placement mode. -->
  <Q1:PlacementMode>false</Q1:PlacementMode>

  <!-- Whether or not to enable avatars. -->
  <Q1:Avatars>false</Q1:Avatars>

  <!-- Whether or not to enable voice control. -->
  <Q1:VoiceControl>false</Q1:VoiceControl>

  <!-- Whether or not to validate XML and the type of response when validation is violated. -->
  <Q1:XmlValidation type="Warning">false</Q1:XmlValidation>
  
  <!-- Type of collider that will be auto-applied to objects missing colliders.
       Options:
          None - no collider is applied
          Box - box collider is applied to the mesh bounds
          NonConvex - non-convex collider (voxel colliders) is applied -->
  <Q1:ColliderMode>Box</Q1:ColliderMode>
  
  <!-- DO NOT MODIFY AFTER THIS LINE. -->
</Q1:Configuration>
