=== nasa/Mixed-Reality-Exploration-Toolkit/Schema/XSD/SchemaFiles/v0.1/TextAnnotation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/MRET"
	elementFormDefault="qualified"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:mt="http://www.example.org/MRET">
	
	<include schemaLocation="Common.xsd"/>

	<complexType name="TextAnnotation">
		<sequence>
			<element name="Texts" type="mt:TextListType"></element>
			<element name="TimePerText" type="float"></element>
			<element name="Loop" type="boolean"></element>
			<element name="AttachTo" type="string"></element>
		</sequence>
		<attribute name="Version" type="string"></attribute>
	</complexType>

	<element name="TextAnnotation" type="mt:TextAnnotation"/>
</schema>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Content/Annotations/TutorialText3.xml
<?xml version="1.0" encoding="UTF-8"?>

<mt:TextAnnotation xsi:schemaLocation="http://www.example.org/MRET TextAnnotation.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mt="http://www.example.org/MRET">

<mt:Texts>

<mt:Texts>Next, we will go over walking in MRET.</mt:Texts>

<mt:Texts>Open the menu, and navigate to the Locomotion section.</mt:Texts>

<mt:Texts>Select the "walking" button with the trigger, and deselect the "teleportation" button.</mt:Texts>

<mt:Texts>Note: you can have multiple locomotion modes active at once, so make sure to turn off what you do not want to use.</mt:Texts>

<mt:Texts>Now walk down the hallway and enter the next part of the tutorial!</mt:Texts>

</mt:Texts>

<mt:TimePerText>7</mt:TimePerText>

<mt:Loop>true</mt:Loop>

<mt:AttachTo>TutorialMenuWalking/Canvas/TutorialTextWalking</mt:AttachTo>

</mt:TextAnnotation>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Content/Annotations/TutorialText2.xml
<?xml version="1.0" encoding="UTF-8"?>

<mt:TextAnnotation xsi:schemaLocation="http://www.example.org/MRET TextAnnotation.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mt="http://www.example.org/MRET">

<mt:Texts>

<mt:Texts>You can change the mode of locomotion through the in-game menu.</mt:Texts>

<mt:Texts>Open then menu by pressing the primary button on either controller.</mt:Texts>

<mt:Texts>Navigate the menu by using your other hand to select buttons with the trigger button.</mt:Texts>

<mt:Texts>Switch pages by selecting the arrow button at the bottom right of each page.</mt:Texts>

<mt:Texts>Press the primary button again on the hand holding the menu to close it.</mt:Texts>

</mt:Texts>

<mt:TimePerText>7</mt:TimePerText>

<mt:Loop>true</mt:Loop>

<mt:AttachTo>TutorialMenuWalking/Canvas/TutorialTextMenu</mt:AttachTo>

</mt:TextAnnotation>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Content/Annotations/TutorialText5.xml
<?xml version="1.0" encoding="UTF-8"?>

<mt:TextAnnotation xsi:schemaLocation="http://www.example.org/MRET TextAnnotation.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mt="http://www.example.org/MRET">

<mt:Texts>

<mt:Texts>You have now completed the Locomotion section of the MRET Tutorial.</mt:Texts>

<mt:Texts>Choose whichever locomotion system you like the best to navigate the rest of MRET!</mt:Texts>

<mt:Texts>In the next section, you will learn about interable objects and different menu features.</mt:Texts>

</mt:Texts>

<mt:TimePerText>7</mt:TimePerText>

<mt:Loop>true</mt:Loop>

<mt:AttachTo>TutorialMenuEnd/Canvas/TutorialTextEnd</mt:AttachTo>

</mt:TextAnnotation>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Content/Annotations/TutorialText1.xml
<?xml version="1.0" encoding="UTF-8"?>

<mt:TextAnnotation xsi:schemaLocation="http://www.example.org/MRET TextAnnotation.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mt="http://www.example.org/MRET">

<mt:Texts>

<mt:Texts>Welcome to the MRET (Mixed Reality Exploration Toolkit) Tutorial!</mt:Texts>

<mt:Texts>In this section, we will be going over the different modes of Locomotion you can choose from. They include teleporting, flying, and walking!</mt:Texts>

<mt:Texts>First, we will go over teleporting. You can do this by aiming your controller at where you wish to go, and pressing the trigger button.</mt:Texts>

<mt:Texts>If your teleport line is green, that means you can teleport to that position. If it is red, you cannot teleport there.</mt:Texts>

<mt:Texts>Try using teleportation to cross the room!</mt:Texts>

</mt:Texts>

<mt:TimePerText>7</mt:TimePerText>

<mt:Loop>true</mt:Loop>

<mt:AttachTo>TutorialMenu/Canvas/TutorialText</mt:AttachTo>

</mt:TextAnnotation>

=== nasa/Mixed-Reality-Exploration-Toolkit/Unity/Assets/Content/Annotations/TutorialText4.xml
<?xml version="1.0" encoding="UTF-8"?>

<mt:TextAnnotation xsi:schemaLocation="http://www.example.org/MRET TextAnnotation.xsd " xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mt="http://www.example.org/MRET">

<mt:Texts>

<mt:Texts>Lastly, we will go over flying in MRET.</mt:Texts>

<mt:Texts>Go to the locomotion section of the menu once more, and select the "flying" button. Remember to turn off walking!</mt:Texts>

<mt:Texts>You use your hands (controllers) and trigger buttons to fly.</mt:Texts>

<mt:Texts>Aim at something in the distance, press the trigger button, and pull yourself towards the object.</mt:Texts>

<mt:Texts>Try aiming and pulling yourself towards the blue orbs to fly across the room!</mt:Texts>

</mt:Texts>

<mt:TimePerText>7</mt:TimePerText>

<mt:Loop>true</mt:Loop>

<mt:AttachTo>TutorialMenuFlying/Canvas/TutorialTextFly</mt:AttachTo>

</mt:TextAnnotation>
